?- use_module(library(clpfd)).
%objectif, resoudre les deux problemes proposés dans l'énoncé

prob1(JAPONAIS, ANGLAIS, ESPAGNOL, SERPENT, ESCARGOT, JAGUAR, ROUGE, BLEUE, AUTRE) :-
Vars = [JAPONAIS, ANGLAIS, ESPAGNOL, SERPENT, ESCARGOT, JAGUAR, ROUGE, BLEUE, AUTRE],
Vars ins 0..2,
Pays = [JAPONAIS, ANGLAIS, ESPAGNOL],
Animaux = [SERPENT, ESCARGOT, JAGUAR],
Couleur = [ROUGE, BLEUE, AUTRE],
all_different(Animaux),
all_different(Pays),
all_different(Couleur),

ANGLAIS #= A #/\ ROUGE #= A,
ESPAGNOL #= B #/\ JAGUAR #=B,
JAPONAIS #= C #/\ ESCARGOT #= (C-1),
ESCARGOT #= D #/\ BLEUE #= (D+1).
%Commande envoyé: prob1(JAPONAIS, ANGLAIS, ESPAGNOL, SERPENT, ESCARGOT, JAGUAR, ROUGE, BLEUE, AUTRE), label([ANGLAIS, JAPONAIS, ESPAGNOL]).

%Reponse: SERPENT = 1

prob2(JAPONAIS, ANGLAIS, ESPAGNOL, NORVEGIEN, UKRAINIEN, CHIEN, ESCARGOT, RENARD, CHEVAL, ZEBRE, SCULPTEUR, DIPLOMATE, VIOLONISTE, MEDECIN, ACROBATE, CAFE, THE, LAIT, ORANGEJUICE, EAU, ROUGE, VERT, BLANC, BLEUE, JAUNE):-
Vars = [JAPONAIS, ANGLAIS, ESPAGNOL, NORVEGIEN, UKRAINIEN, CHIEN, ESCARGOT, RENARD, CHEVAL, ZEBRE, SCULPTEUR, DIPLOMATE, VIOLONISTE, MEDECIN, ACROBATE, CAFE, THE, LAIT, ORANGEJUICE, EAU, ROUGE, VERT, BLANC, BLEUE, JAUNE],
Vars ins 0..4,


Pays = [JAPONAIS, ANGLAIS, ESPAGNOL, NORVEGIEN, UKRAINIEN],
Animaux = [CHIEN, ESCARGOT, RENARD, CHEVAL, ZEBRE],
Job = [SCULPTEUR, DIPLOMATE, VIOLONISTE, MEDECIN, ACROBATE],
Drink = [CAFE, THE, LAIT, ORANGEJUICE, EAU],
Couleur = [ROUGE, VERT, BLANC, BLEUE, JAUNE],

all_different(Pays),
all_different(Animaux),
all_different(Job),
all_different(Drink),
all_different(Couleur),

ANGLAIS #= A #/\ ROUGE #= A,
ESPAGNOL #= B #/\ CHIEN #= B,
VERT #= C #/\ CAFE #= C,
UKRAINIEN #= D #/\ THE #= D,
VERT #= E #/\ BLANC #= E-1,
SCULPTEUR #= F #/\ ESCARGOT #= F,
DIPLOMATE #= G #/\ JAUNE #= G,
LAIT #= 2,
NORVEGIEN #= 0,
MEDECIN #= H #/\ RENARD #= H1 #/\ abs(H-H1) #= 1,
DIPLOMATE #= I #/\ CHEVAL #= I1 #/\ abs(I-I1) #= 1,
VIOLONISTE #= K #/\ ORANGEJUICE #= K,
JAPONAIS #= L #/\ ACROBATE #= L,
NORVEGIEN #= M #/\ BLEUE #= M1 #/\ abs(M-M1) #= 1.

%Commande Envoye : prob2(JAPONAIS, ANGLAIS, ESPAGNOL, NORVEGIEN, UKRAINIEN, CHIEN, ESCARGOT, RENARD, CHEVAL, ZEBRE, SCULPTEUR, DIPLOMATE, VIOLONISTE, MEDECIN, ACROBATE, CAFE, THE, LAIT, ORANGEJUICE, EAU, ROUGE, VERT, BLANC, BLEUE, JAUNE), label([EAU, THE, CAFE, LAIT, ORANGEJUICE]).

%Reponse: EAU = 0 (celle la plus a gauche, avec le norvegien, ZEBRE = 4, celle la plus a droite avec le japonais.


